---
version: '3'

services:
  zammad-elasticsearch:
    environment:
      VIRTUAL_HOST: '{{ zammad_elasticsearch_domain }}'
      LETSENCRYPT_HOST: '{{ zammad_elasticsearch_domain }}'
      LETSENCRYPT_EMAIL: '{{ letsencrypt_email }}'
      VIRTUAL_PORT: 9200
    networks:
      - default
      - webproxy
