---
# defaults file for minio
minio_path: '/container/minio'

minio_domain: 'minio.{{ ansible_fqdn }}'
minio_addon_domains: []
minio_domains: '{{ [minio_domain] + minio_addon_domains }}'

minio_data_path: './data'

minio_console_domain: 'minio-console.{{ ansible_fqdn }}'
minio_console_letsencrypt_host: '{{ minio_console_domain }}'

# enable the console container for minio
minio_console_enable: false

# to be replaced in host_vars
# USE YOUR OWN, RANDOM SECRETS HERE!
# minio_root_user: 'blafoo'
# minio_root_password: 'barfoo'
# minio_console_pbkdf_passphrase: 'blafoo'
# minio_console_pbkdf_salt: 'barfoo'

minio_version: latest
minio_console_version: latest

# pull docker images (docker-compose pull)
minio_docker_pull: '{{ global_docker_pull | default(False) }}'
